//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CD_DAL.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CD_DataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CD_DataEntities object using the connection string found in the 'CD_DataEntities' section of the application configuration file.
        /// </summary>
        public CD_DataEntities() : base("name=CD_DataEntities", "CD_DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CD_DataEntities object.
        /// </summary>
        public CD_DataEntities(string connectionString) : base(connectionString, "CD_DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CD_DataEntities object.
        /// </summary>
        public CD_DataEntities(EntityConnection connection) : base(connection, "CD_DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CD_Countries> CD_Countries
        {
            get
            {
                if ((_CD_Countries == null))
                {
                    _CD_Countries = base.CreateObjectSet<CD_Countries>("CD_Countries");
                }
                return _CD_Countries;
            }
        }
        private ObjectSet<CD_Countries> _CD_Countries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CD_EntityTypes> CD_EntityTypes
        {
            get
            {
                if ((_CD_EntityTypes == null))
                {
                    _CD_EntityTypes = base.CreateObjectSet<CD_EntityTypes>("CD_EntityTypes");
                }
                return _CD_EntityTypes;
            }
        }
        private ObjectSet<CD_EntityTypes> _CD_EntityTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CD_Languages> CD_Languages
        {
            get
            {
                if ((_CD_Languages == null))
                {
                    _CD_Languages = base.CreateObjectSet<CD_Languages>("CD_Languages");
                }
                return _CD_Languages;
            }
        }
        private ObjectSet<CD_Languages> _CD_Languages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CD_Users> CD_Users
        {
            get
            {
                if ((_CD_Users == null))
                {
                    _CD_Users = base.CreateObjectSet<CD_Users>("CD_Users");
                }
                return _CD_Users;
            }
        }
        private ObjectSet<CD_Users> _CD_Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CD_Countries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCD_Countries(CD_Countries cD_Countries)
        {
            base.AddObject("CD_Countries", cD_Countries);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CD_EntityTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCD_EntityTypes(CD_EntityTypes cD_EntityTypes)
        {
            base.AddObject("CD_EntityTypes", cD_EntityTypes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CD_Languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCD_Languages(CD_Languages cD_Languages)
        {
            base.AddObject("CD_Languages", cD_Languages);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CD_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCD_Users(CD_Users cD_Users)
        {
            base.AddObject("CD_Users", cD_Users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CD_DataModel", Name="CD_Countries")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CD_Countries : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CD_Countries object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static CD_Countries CreateCD_Countries(global::System.String code, global::System.String name)
        {
            CD_Countries cD_Countries = new CD_Countries();
            cD_Countries.Code = code;
            cD_Countries.Name = name;
            return cD_Countries;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CD_DataModel", Name="CD_EntityTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CD_EntityTypes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CD_EntityTypes object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CD_EntityTypes CreateCD_EntityTypes(global::System.Int32 id)
        {
            CD_EntityTypes cD_EntityTypes = new CD_EntityTypes();
            cD_EntityTypes.ID = id;
            return cD_EntityTypes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CD_DataModel", Name="CD_Languages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CD_Languages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CD_Languages object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CD_Languages CreateCD_Languages(global::System.Int32 id)
        {
            CD_Languages cD_Languages = new CD_Languages();
            cD_Languages.ID = id;
            return cD_Languages;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CD_DataModel", Name="CD_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CD_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CD_Users object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CD_Users CreateCD_Users(global::System.Int64 id)
        {
            CD_Users cD_Users = new CD_Users();
            cD_Users.ID = id;
            return cD_Users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Salt
        {
            get
            {
                return _Salt;
            }
            set
            {
                OnSaltChanging(value);
                ReportPropertyChanging("Salt");
                _Salt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Salt");
                OnSaltChanged();
            }
        }
        private global::System.String _Salt;
        partial void OnSaltChanging(global::System.String value);
        partial void OnSaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                OnBirthDateChanging(value);
                ReportPropertyChanging("BirthDate");
                _BirthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BirthDate");
                OnBirthDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BirthDate;
        partial void OnBirthDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthDateHeb
        {
            get
            {
                return _BirthDateHeb;
            }
            set
            {
                OnBirthDateHebChanging(value);
                ReportPropertyChanging("BirthDateHeb");
                _BirthDateHeb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BirthDateHeb");
                OnBirthDateHebChanged();
            }
        }
        private global::System.String _BirthDateHeb;
        partial void OnBirthDateHebChanging(global::System.String value);
        partial void OnBirthDateHebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EGenderID
        {
            get
            {
                return _EGenderID;
            }
            set
            {
                OnEGenderIDChanging(value);
                ReportPropertyChanging("EGenderID");
                _EGenderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EGenderID");
                OnEGenderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EGenderID;
        partial void OnEGenderIDChanging(Nullable<global::System.Int32> value);
        partial void OnEGenderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastVisitDate
        {
            get
            {
                return _LastVisitDate;
            }
            set
            {
                OnLastVisitDateChanging(value);
                ReportPropertyChanging("LastVisitDate");
                _LastVisitDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastVisitDate");
                OnLastVisitDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastVisitDate;
        partial void OnLastVisitDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastVisitDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastVisitIP
        {
            get
            {
                return _LastVisitIP;
            }
            set
            {
                OnLastVisitIPChanging(value);
                ReportPropertyChanging("LastVisitIP");
                _LastVisitIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastVisitIP");
                OnLastVisitIPChanged();
            }
        }
        private global::System.String _LastVisitIP;
        partial void OnLastVisitIPChanging(global::System.String value);
        partial void OnLastVisitIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStamp;
        partial void OnTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampChanged();

        #endregion
    
    }

    #endregion
    
}
